### ISSUE TITLE
Add an option to manually specify the modbus function

### ISSUE THREAD

**Issue by feuri** [RichiH/modbus_exporter#14]
I'm trying to read values from an ABB B23 power meter which seems to not follow modbus standards. The holding registers that hold the data I want to read start at address 20480 (0x5000 as mentioned in the manual).
An option to manually specify the modbus function would be needed to read data from these kind of devices.

I'd be happy to try and get this implemented, though I have not used Go yet.

**Comment by RichiH** [comment]
If you want to send a PR, that would be great.
