### ISSUE TITLE
Scaling values

### ISSUE THREAD

**Issue by braamvh** [RichiH/modbus_exporter#15]
Is there a way to scale the values read from Modbus?

In my case I read a number of values off an inverter controller, with all returns being Int or UInt. However, values are scaled where they have decimals.

Example: Battery voltage is returned as 5281 where the real value is 52.81V, while the input voltage is returned as 2303 for 230.3V.

I've looked through the code, but can't see a way to add a scaling factor where the metric is read.

**Comment by dshatohin** [comment]
IMO idea behind that is just to give you the real value from modbus register and then transform it by Prometheus.
I'm using PromQL in Grafana exactly the same way - to convert 2300V to 230.0V.

**Comment by braamvh** [comment]
Ahhh, I see. Thanks, will try that.

**Comment by rfc1036** [comment]
I think that simple scaling like divide by 1000 would still be very useful to better handle instruments which use fixed point arithmetic.

Currently I have to create different Grafana dashboards for different instruments: even if I can normalize the register maps differences to return the same metric with the same name, they still often require different scaling.

**Comment by SuperQ** [comment]
Ping @RichiH, IMO this is probably worth doing.

**Comment by RichiH** [comment]
I am wondering what the config syntax should be. `factor = n` would seem prudent?

**Comment by braamvh** [comment]
`scalefactor = n`, perhaps?  Then just multiply by the value.  So if scalefactor is 0.1 it would divide by 10, and if it is 10 it would multiply by 10. I think that should handle any factors that comes up.

**Comment by RichiH** [comment]
I considered `scale` etc, but it might not always be in powers of ten and rather than get into the mathematical weeds thought to keep it simple.
