### ISSUE TITLE
Collect modbus.yml for different vendors

### ISSUE THREAD

**Issue by RiRa12621** [RichiH/modbus_exporter#8]
Adding all values to the modbus.yml is a very tedious work.
Doing that once should be enough so it might be good to collect those for vendors/products.
This could be done in a folder and people using the exporter could go through the files, to find out if what they need has already been done.

**Comment by dssantana** [comment]
In our particular case, we had all modbus information in a spreadsheet, so we wrote a basic phyton app to create the yml from the spreadsheet. Just a thought

**Comment by RiRa12621** [comment]
I fully agree that this can be done and it’s what I will do as well.
I was thinking of this for folks who are not very technically versed and still would like to get visibility on appliances they own like smart heating or power meters.
It’s a lot easier to say “run this docker command and use the file for your device” than “write a script to get the values you need into the right format”

**Comment by RichiH** [comment]
If you want to submit anything, I will gladly add it. I am planning to do the same once I have stable configurations

**Comment by RiRa12621** [comment]
great, I'll try to find some time to get something ready 👍

**Comment by rfc1036** [comment]
I have some configurations that I am happy to share, but I first need to see how issue #9 goes.

**Comment by RiRa12621** [comment]
Absolutely can't find the time. Fine to close imho.
